### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by fulldecent** [comment]
Please add a large notice here that this repository is DEPRECATED.

@mheadd
@laurenancona

This PR does that for you with one click!

**Comment by mheadd** [comment]
Makes sense to me. Someone in the City of Philadelphia org will have to merge this. /cc: @timwis

**Comment by fulldecent** [comment]
Pinging members of https://github.com/orgs/CityOfPhiladelphia/people

May we please find a reviewer for this PR?

@awm33
@jamesmbentley
@rbrtmrtn
@timwis
@tswanson

**Comment by timwis** [comment]
Pardon my delay @fulldecent, only my fault! Thanks for submitting.

**Pull request merged**
